### ISSUE TITLE
jfreechart invalid dependency

### ISSUE THREAD

**Issue by williamvoor** [dwdyer/uncommons-maths#3]
I'm unable to fully build this project using maven, as it depends on jfreechar 1.0.8. This version doesn't exist in the main maven repo. There's only 1.0.8a. See http://mvnrepository.com/artifact/jfree/jfreechart/

If I'm doing something wrong, please let me know. Thanks!

**Comment by dwdyer** [comment]
Since the project has never used Maven for building, I assume this is something you have configured yourself.  You should be fine setting the dependency to a later version of JFreechart.  It is only used by the demo module, not the core library.

**Comment by williamvoor** [comment]
I'm sorry, but I explained the issue incorrectly. I'll try to make myself clear.
I'm not really trying to build uncommons-math using Maven.
What I was trying to do was building Watchmaker using Maven. It indirectly depends on jfreechart 1.0.8 via uncommons-math. I could see the dependency here: http://mvnrepository.com/artifact/org.uncommons.maths/uncommons-maths/1.2.2
When building Watchmaker, I get the following error:

  Path to dependency: 
    1) org.uncommons.watchmaker:watchmaker-framework:jar:0.7.2
    2) org.uncommons.maths:uncommons-maths:jar:1.2.2
    3) jfree:jfreechart:jar:1.0.8

---

1 required artifact is missing.

**Comment by buka** [comment]
It would be great if the published POM could be fixed. Mahout 0.6 cannot be fully obtained from the Maven repo because of this breakage as well. This impacts any build system (SBT, etc) not just Maven...

**Comment by dwdyer** [comment]
What is the source of this problem?  The POM for Uncommons Maths doesn't list a dependency on JFreeChart because JFreeChart is only needed by the demo module, which other projects should not be depending on.  The Swing module of Watchmaker does have a dependency on JFreeChart but that is nothing to do with Uncommons Maths and it is a different version.

I think you need to find who was responsible for uploading Uncommons Maths to the Maven repository with the wrong dependencies and get them to fix it.

**Comment by johansen** [comment]
Looks like this is fixed in uncommons-maths 1.2.2a on Maven Central.

**Comment by dwdyer** [comment]
OK, thanks for letting me know.  I'll close this issue.
